// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using System;

namespace leta.Model.Migrations
{
    [DbContext(typeof(LetaAppDbContext))]
    [Migration("20210510225953_Initial-Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("leta.webApp.Data.RouteTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DiaDaSemana")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DiaDoMes")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("HoraDoDia")
                        .HasColumnType("time(6)");

                    b.Property<int>("Tempo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RouteTime");
                });
#pragma warning restore 612, 618
        }
    }
}
