// This file was auto-generated by ML.NET Model Builder. 

using System;
using Microsoft.ML.Data;

namespace leta.Application.ViewModels
{
    public class ModelOutput
    {
        public float[] MediaDeTempo { get; set; }
        //public float[] MaioresTempos { get; set; }
        //public float[] MenoresTempos { get; set; }
    }
}
