// This file was auto-generated by ML.NET Model Builder. 

using System;
using Microsoft.ML.Data;

namespace leta.Model
{
    public class ModelOutput
    {
        public float[] MediaDeTempo { get; set; }
        public float[] MaioresTempso { get; set; }
        public float[] MenoresTempos { get; set; }
    }
}
