// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using leta.Data;

namespace leta.Data.Migrations
{
    [DbContext(typeof(LetaAppDbContext))]
    partial class LetaAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("leta.Data.RouteTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DiaDaSemana")
                        .HasColumnType("int");

                    b.Property<DateTime>("HoraDoDia")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("Tempo")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("RouteTime");
                });
#pragma warning restore 612, 618
        }
    }
}
